# Generated by Django 4.0.6 on 2022-07-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBookAuthor', '0002_books_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authors',
            table='tbl_authors',
        ),
        migrations.AlterModelTable(
            name='books',
            table='tbl_books',
        ),
        migrations.AlterModelTable(
            name='booktype',
            table='tbl_book_type',
        ),
    ]
