# Generated by Django 4.0.6 on 2022-07-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBookAuthor', '0003_alter_authors_table_alter_books_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='books',
        ),
    ]
